 
  
  
  update NOVMVM_DETT  set MMCODUBI=MMCODMAG, MMLOTMAG=MMCODMAG where COALESCE(DATALENGTH(LTRIM(RTRIM(MMCODUBI))),0) = 0  AND COALESCE(DATALENGTH(LTRIM(RTRIM(MMLOTMAG))),0) = 0  AND MMCODMAG = '02' 
  
