import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  async redirects() {
    return [
      { source: "/index.html", destination: "/", permanent: true },
      { source: "/assistenza.html", destination: "/assistenza", permanent: true },
      { source: "/assistenza_1.html", destination: "/assistenza", permanent: true },
      { source: "/assistenza_1", destination: "/assistenza", permanent: true },
      { source: "/servizi.html", destination: "/servizi", permanent: true },
      { source: "/servizi_fatel.html", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi_backup.html", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi_fatel.htm", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi_backup.htm", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi_fatel", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi_backup", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi_fatell", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi_bakcup", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi-fatel", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi-backup", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi-fatel.html", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi-backup.html", destination: "/servizi/business-continuity", permanent: true },
      { source: "/business-continue", destination: "/servizi/business-continuity", permanent: true },
      { source: "/business-continuite", destination: "/servizi/business-continuity", permanent: true },
      { source: "/business-continuity.html", destination: "/servizi/business-continuity", permanent: true },
      { source: "/prodotti_digitali.html", destination: "/firma-digitale", permanent: true },
      { source: "/firma_digitale.html", destination: "/firma-digitale", permanent: true },
      { source: "/prodotti_digitali", destination: "/firma-digitale", permanent: true },
      { source: "/firma_digitale", destination: "/firma-digitale", permanent: true },
      { source: "/prodotti-digitali", destination: "/firma-digitale", permanent: true },
      { source: "/prodotti-digitali.html", destination: "/firma-digitale", permanent: true },
      { source: "/firma-digitale.html", destination: "/firma-digitale", permanent: true },
      { source: "/forniture_mepa.html", destination: "/mepa", permanent: true },
      { source: "/forniture_mepa", destination: "/mepa", permanent: true },
      { source: "/forniture-mepa", destination: "/mepa", permanent: true },
      { source: "/forniture-mepa.html", destination: "/mepa", permanent: true },
      { source: "/gestionale_azienda.html", destination: "/gestionale", permanent: true },
      { source: "/gestionale_ordini.html", destination: "/gestionale", permanent: true },
      { source: "/gestionale_azienda", destination: "/gestionale", permanent: true },
      { source: "/gestionale_ordini", destination: "/gestionale", permanent: true },
      { source: "/gestionale-azienda", destination: "/gestionale", permanent: true },
      { source: "/gestionale-ordini", destination: "/gestionale", permanent: true },
      { source: "/servizi/servizi_fatel", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi/servizi_backup", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi/servizi_fatel.html", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi/servizi_backup.html", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi/servizi-fatel", destination: "/servizi/fatturazione-elettronica", permanent: true },
      { source: "/servizi/servizi-backup", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi/gestionale_azienda", destination: "/servizi/gestionale-su-misura", permanent: true },
      { source: "/servizi/gestionale-azienda", destination: "/servizi/gestionale-su-misura", permanent: true },
      { source: "/servizi/forniture_mepa", destination: "/servizi/tecnologia-didattica", permanent: true },
      { source: "/servizi/forniture-mepa", destination: "/servizi/tecnologia-didattica", permanent: true },
      { source: "/servizi/prodotti_digitali", destination: "/servizi/firma-digitale", permanent: true },
      { source: "/servizi/firma_digitale", destination: "/servizi/firma-digitale", permanent: true },
      { source: "/servizi/firma_digitale.html", destination: "/servizi/firma-digitale", permanent: true },
      { source: "/servizi/prodotti_digitali.html", destination: "/servizi/firma-digitale", permanent: true },
      { source: "/servizi/prodotti-digitali", destination: "/servizi/firma-digitale", permanent: true },
      { source: "/servizi/firma-digitale.html", destination: "/servizi/firma-digitale", permanent: true },
      { source: "/servizi/business-continue", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi/business-continuite", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi/businesscontinuity", destination: "/servizi/business-continuity", permanent: true },
      { source: "/servizi/mepa", destination: "/servizi/tecnologia-didattica", permanent: true },
      { source: "/servizi/whistle-blowing", destination: "/servizi/whistleblowing", permanent: true },
      { source: "/servizi/whisteblowing", destination: "/servizi/whistleblowing", permanent: true },
      { source: "/servizi/wistleblowing", destination: "/servizi/whistleblowing", permanent: true },
      { source: "/servizi/:slug.html", destination: "/servizi/:slug", permanent: true },
      { source: "/contatti.html", destination: "/contatti", permanent: true },
      { source: "/privacy.html", destination: "/privacy", permanent: true },
      { source: "/whistleblowing.html", destination: "/whistleblowing", permanent: true },
      { source: "/prova.html", destination: "/privacy", permanent: true },
    ];
  },
};

export default nextConfig;
