vti_encoding:SR|utf8-nl
vti_timelastmodified:TR|07 Nov 2008 09:33:24 -0000
vti_extenderversion:SR|4.0.2.8912
vti_cacheddtm:TX|07 Nov 2008 09:33:24 -0000
vti_filesize:IR|1058
vti_cachedlinkinfo:VX|S|bar.asp F|BAR.ASP F|NOTE.HTM
vti_cachedsvcrellinks:VX|FSUS|upload/bar.asp FFUS|upload/BAR.ASP NFUS|upload/NOTE.HTM
vti_cachedtitle:SR|sto caricando...
vti_title:SR|sto caricando...
vti_cachedbodystyle:SR|<BODY BGCOLOR="#C0C0B0">
vti_cachedhasbots:BR|false
vti_cachedhastheme:BR|false
vti_cachedhasborder:BR|false
vti_hasframeset:BR|true
vti_backlinkinfo:VX|
