--------------------------------
--  MOVIMENTI MAGA
--------------------------------
select MMCODMAG, MMLOTMAG,MMFLLOTT,MMCODUBI, *  
  from NOVMVM_DETT 
 where MMCODMAG NOT IN ('02')
   AND  COALESCE(DATALENGTH(LTRIM(RTRIM(MMCODLOT))),0)<> 0 
   AND (COALESCE(DATALENGTH(LTRIM(RTRIM(MMLOTMAG))),0) = 0 
    OR  COALESCE(DATALENGTH(LTRIM(RTRIM(MMFLLOTT))),0) = 0)
   AND  cpccchk= 'DIP130924A' 


update NOVMVM_DETT set MMLOTMAG = MMCODMAG , MMFLLOTT = MMFLCASC , cpccchk= 'DIP131001A' 
 where MMCODMAG NOT IN ('02')
   AND  COALESCE(DATALENGTH(LTRIM(RTRIM(MMCODLOT))),0)<> 0 
   AND (COALESCE(DATALENGTH(LTRIM(RTRIM(MMLOTMAG))),0) = 0 
    OR  COALESCE(DATALENGTH(LTRIM(RTRIM(MMFLLOTT))),0) = 0) 
   AND  cpccchk= 'DIP130924A' 
-------------------------------  
--   DOCUMENTI
-------------------------------  
select MVCODMAG, MVLOTMAG,MVFLLOTT,MVCODUBI, *  
  from NOVDOC_dett 
 where MVCODMAG NOT IN ('02')
   AND  COALESCE(DATALENGTH(LTRIM(RTRIM(MVCODLOT))),0)<> 0 
   AND (COALESCE(DATALENGTH(LTRIM(RTRIM(MVLOTMAG))),0) = 0 
    OR  COALESCE(DATALENGTH(LTRIM(RTRIM(MVFLLOTT))),0) = 0)
   AND  cpccchk= 'DIP130924A'    

update NOVDOC_DETT set MVLOTMAG = MVCODMAG , MVFLLOTT = MVFLCASC , cpccchk= 'DIP131001A'
 where MVCODMAG NOT IN ('02')
   AND  COALESCE(DATALENGTH(LTRIM(RTRIM(MVCODLOT))),0)<> 0 
   AND (COALESCE(DATALENGTH(LTRIM(RTRIM(MVLOTMAG))),0) = 0 
    OR  COALESCE(DATALENGTH(LTRIM(RTRIM(MVFLLOTT))),0) = 0)
   AND  cpccchk= 'DIP130924A'  
---------------------------------    
--  BUONI
---------------------------------
select MVCODMAG, MVLOTMAG,MVFLLOTT,MVCODUBI, *  
  from NOVBNC_dett
 where MVCODMAG NOT IN ('02')
   AND  COALESCE(DATALENGTH(LTRIM(RTRIM(MVCODLOT))),0)<> 0 
   AND (COALESCE(DATALENGTH(LTRIM(RTRIM(MVLOTMAG))),0) = 0 
    OR  COALESCE(DATALENGTH(LTRIM(RTRIM(MVFLLOTT))),0) = 0)
   AND  cpccchk= 'DIP130924A'

update NOVBNC_DETT set MVLOTMAG = MVCODMAG , MVFLLOTT = MVFLCASC , cpccchk= 'DIP131001A'
 where MVCODMAG NOT IN ('02')
   AND  COALESCE(DATALENGTH(LTRIM(RTRIM(MVCODLOT))),0)<> 0 
   AND (COALESCE(DATALENGTH(LTRIM(RTRIM(MVLOTMAG))),0) = 0 
    OR  COALESCE(DATALENGTH(LTRIM(RTRIM(MVFLLOTT))),0) = 0)
   AND  cpccchk= 'DIP130924A'    

